#!/bin/bash

echo "Solve an equation of the form x=(a+b)/c"

read -p "Enter number a = " a
read -p "Enter number b = " b
read -p "Enter number c = " c

function funcA {
echo "scale=5; ($a+$b)/$c" | bc
}

funcA
