#!/bin/bash

cat /etc/passwd | awk -F ":" '{print $3,$1}' > fileUsers

while :
do
  cat /etc/passwd | awk -F ":" '{print $3,$1}' > fileTemp
  diff fileUsers fileTemp | sed '1d' | awk '{print $2,$3}' >> fileUsers
  sleep 300
done
