#!/bin/bash
# Go to home directory
cd
# Create file with extended recursive listing of the home directory
ls -Rl > filedir2
echo "file in the home directory"
# Username replacement with sed
sed 's/bobrov/superman/' ./filedir2 > fileX
# Delete string with total files
sed '/total/d' fileX > file483
# Delete temporary files
rm filedir2 fileX

