#!/bin/bash
# Go to home directory
cd
# Create file with extended recursive listing of the home directory
ls -RFl > filedir2
echo "file in the home directory"
# Show only files
sed '/\/$\|^$\|^\.\|total/d' filedir2 > fileF
# Show files with extension
awk '$9 ~ /\..*$/ {print $9}' fileF > file486
# Delete temporary files
rm fileF filedir2
