#!/bin/bash

echo "User's home directory"
echo "<$USER>"
echo "Contains regular files:"
find ~ -maxdepth 1 -type f \! -name ".*" | wc -l
echo "Hidden files:"
find ~ -maxdepth 1 -type f -name ".*" | wc -l
